### ISSUE TITLE
I used the dump command (x) on the AE2 terminal and everything in my inventory was destroyed

### ISSUE THREAD

**Issue by udooles** [MindBrain27/Sky-Greg#1]
I pressed the X key by accident while hovering over my AE2 terminal and got a message everything in my inventory was deposited however nothing was in my AE2 system and it seemed to be destroyed.  I had just started a new world so restarted my world but it seems this mod and AE2 don't play well together.

**Comment by MindBrain27** [comment]
Interesting, I will play around with that and see if I can blacklist certain inventories after work. Just to be sure, they didn't go into the Aluminium Crates where the cobble or dirt gens are correct? If I cant blacklist inventories then I'll end up removing quickstack unfortunately. Will look into after work.

**Comment by MindBrain27** [comment]
Blacklisting ae2 blocks fixed it, will update tonight. If you want a quicker fix you can update this line in the quickstack config file 

	"Blacklisted Block Entities" = ["minecraft:furnace", "minecraft:blast_furnace", "minecraft:smoker"]

to

	"Blacklisted Block Entities" = ["minecraft:furnace", "minecraft:blast_furnace", "minecraft:smoker", "ae2:molecular_assembler", "ae2:pattern_provider", "ae2:cable_pattern_provider", "ae2:drive"]

I noticed items would also be placed in the Molecular Assembler and Pattern Provider as well, I tried an ME Chest but it was already fine. I may be missing more ae2 inventory blocks but not sure.

**Comment by MindBrain27** [comment]
Changes live.
