### ISSUE TITLE
saturation item on off hand only work hotkey 1 only?

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#10]
is saturation item on off hand only work hotkey 1 only?

**Comment by MindBrain27** [comment]
I didn't notice that but yes that seems to be correct, I thought it only worked in the main hand to be honest, I'm going to tinker with that tonight and see if I can make it work normally in both hands.

**Comment by MindBrain27** [comment]
Well I have 2 options for now. I can either disable it completely in the off hand so it only works in the main hand, or I can just ignore it and leave it as it is. It's a strange bug I can't fix right now but I can make it more uniform only working in the main hand.

**Comment by akasia** [comment]
nvm just let you know cos is so strange bug just work on off hand and hot key 1 
ignore it batter than main hand only

**Comment by MindBrain27** [comment]
I will leave it as is but still try and fix the issue somehow to make it work normally in both hands.

**Comment by MindBrain27** [comment]
For now I added quest text stating to use your main hand, I am going to close this for now as I still can't fix the bug but am working on it.

**Comment by MindBrain27** [comment]
Fixed with next update, works in both hands normally.
