### ISSUE TITLE
your quest say 6 iron lava furnace can supply 1 large steam boiler how come my setup with 24 iron lava furnace still can't keep up with 2 boiler?

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#12]
how come my setup with 24 iron lava furnace can't keep up with 2 boiler? ar my math wrong or ratio is worng?

![2024-01-02_23 54 18](https://github.com/MindBrain27/Sky-Greg/assets/14824981/1ae0367a-83eb-4581-b0f7-586316a3e458)

**Comment by MindBrain27** [comment]
One thing i may have not mentioned is the throttle setting in the boiler, set the throttle to the lowest it can go (25%) then turn it back up once it is running, that's what I did but I wasn't sure if it was required or not, try turning the throttle down and see if that works.

**Comment by MindBrain27** [comment]
I'm not entirely sure how the throttle setting works or if it's working as intended but that seemed to make it work for me.

**Comment by akasia** [comment]
hmm seem like that need low throttle to keed start? weir set up

**Comment by MindBrain27** [comment]
I'll mention something about the throttle in the quest, I wasn't sure if it necessary or not but it seems like it is. I had 18 Iron Lava Furnaces powering 3 Bronze Boilers for a while until I upgraded.

**Comment by MindBrain27** [comment]
I added a note in the quests about the Throttle function, I am going to mark this as closed.

**Comment by akasia** [comment]
nice
