### ISSUE TITLE
Should I add tiered loot bags as quest rewards?

### ISSUE THREAD

**Issue by MindBrain27** [MindBrain27/Sky-Greg#14]
I have been messing around with loot bags ideas for a while and i do have loot bags made for quests split into different tiers, so a
n LV loot bag would have LV crafting components like LV Motors, LV Pistons, LV Cables, LV Machine Hulls, and so on. Currently they have all of the Crafting components for the age, 4x Cables (1 EU loss), and Circuits. It would be easy to add to basically every quest that isn't a checkbox quest.

Post thoughts here, I may add , I may not.

**Comment by akasia** [comment]
that is good ideas

**Comment by Cassa-sys** [comment]
I think it's a nice idea as it makes the pack a bit more accessible for those not too much into GregTech.

**Comment by MindBrain27** [comment]
I added some basic ones for the first few ages, the rest will come later.
