### ISSUE TITLE
Add useful Mod

### ISSUE THREAD

**Issue by bick88** [MindBrain27/Sky-Greg#15]
First of all, great modpack. I hope that  it will become more and more known.

I think adding the Tool Belt mod can be useful. This allows you to switch gregtech tools easily when installing pipe or cable or machine.

**Comment by MindBrain27** [comment]
Thank you! I really appreciate it!

I love the Tool Belt mod and I forgot all about it, will be adding for sure.

**Comment by MindBrain27** [comment]
Has been added, I will close this issue when I update the pack.

**Comment by akasia** [comment]
can request add ae2 things

**Comment by MindBrain27** [comment]
I was thinking that and ME Requester, both will likely be added.

**Comment by akasia** [comment]
olso functional storage may b?

**Comment by MindBrain27** [comment]
I kind of intentionally didn't want any Storage Drawers or mods like that, maybe one of the 2 in the future but not now at least.
