### ISSUE TITLE
request for some way to wireless charge wireless termenal 

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#16]
request for some way to wireless charge wireless termenal ~

**Comment by MindBrain27** [comment]
Good idea, I will look into the Wireless Chargers mod.

https://www.curseforge.com/minecraft/mc-mods/wireless-chargers

**Comment by MindBrain27** [comment]
Added and works well, will be updated tonight.

Note you will need a GregTech Energy Converter as the AE2 Energy Cell will not send power to it. I will close this issue later when I update the pack.

**Comment by akasia** [comment]
nice!
