### ISSUE TITLE
GT steam input bus need block update to trigger auto pull item after reentery world

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#18]
GT steam input bus need block update to trigger auto pull item after reentery world

**Comment by MindBrain27** [comment]
Yes this is for most auto input busses and hatches I noticed, there are a few open issues about this in the GT git hub, my best work around for now is using something like an EnderIO Conduit or LaserIO Node to insert/extract into the busses/hatches. If the bus or hatch is trying to auto pull or push, it can forget on a relog. If you have a Laser Node or Conduit pushing or pulling it seems to be ok. But a GT bus/hatch on auto mode will forget what it was doing on a relog.

Really hoping that one is addressed sooner than later.

This was the biggest reason why I added for piping methods.

**Comment by akasia** [comment]
oh i see than there is no way to automate using dimchest~sad

**Comment by MindBrain27** [comment]
I do Dim Chest, EnderIO Conduit, input bus, the conduit on export mode is good enough to send an update when trying to transfer items, I've had no problems when using a Laser Node or Conduit between the Dim Chest and Input Bus.

**Comment by MindBrain27** [comment]
![2024-01-04_07 37 56](https://github.com/MindBrain27/Sky-Greg/assets/74363414/4e37f2a3-efeb-48e5-9cc8-04c46b7c5a12)

**Comment by akasia** [comment]
yah but like this even more fun
![2024-01-04_21 25 47](https://github.com/MindBrain27/Sky-Greg/assets/14824981/2044d409-7051-4652-b942-fdec43444d3b)

**Comment by MindBrain27** [comment]
Ideally that would be the way, I imagine this would be fixed in an upcoming GT update. I will always post GT update changelogs with my own changelogs as well so just be on the lookout for that.

**Comment by MindBrain27** [comment]
I believe this has been fixed with newest GT update. "fixed distinct buses not working after reloading the world", my testing so far seems to be working, closing this for now.
