### ISSUE TITLE
Missing recipe Concrete for DANK STORAGE MOD

### ISSUE THREAD

**Issue by bick88** [MindBrain27/Sky-Greg#19]
The Dank Storage modpack dock recipe does not work because there is no recipe for black concrete
This item allows you to have almost unlimited drawers. Maybe put a custom recipe with gregtech elements to have it a little later with the LV or MV age

**Comment by MindBrain27** [comment]
Craft Black Concrete Powder then place in water for make Black Concrete. I could add a GT recipe too but that's vanilla mechanics for ya. Currently there is a GT recipe to make White Concrete in a fluid solidifier, but only white, colors and black are made from Powders.

**Comment by MindBrain27** [comment]
Mixer recipes for Concrete Powders to Concretes will be added with next update as well.

**Comment by MindBrain27** [comment]
Done in new update.
