### ISSUE TITLE
Suggestion: Use LaserIO instead of Pipez until Grettech pipes are fixed

### ISSUE THREAD

**Issue by udooles** [MindBrain27/Sky-Greg#2]
Pipez are very basic and can be very annoying to work with in more complex setups because of limited filter options and not being able to insert/extract from the same face.  Please consider using LaserIO instead as it has much better filtering and I/O options.

**Comment by MindBrain27** [comment]
Ooh I like that idea, will definitely do.

**Comment by MindBrain27** [comment]
Added.
