### ISSUE TITLE
Ethylene/Polyethylene Quest Requires Ethanol + Sulfuric Acid Route

### ISSUE THREAD

**Issue by xyrc1** [MindBrain27/Sky-Greg#20]
The MV quest line requires you to obtain ethylene through the intended(?) ethanol + sulfuric acid route, when other options exist. It would be nice to see either other methods shown or remove any dependencies the ethylene quest has.

**Comment by MindBrain27** [comment]
Good point, I'll make that more open and point out the other Glycerol and Distilling routes too. This will be addressed in the next day or two. I will leave this open until the pack updates.
