### ISSUE TITLE
dankstorage can't set frequency or unlock frequency even using command to unlock frequency it comback invalid id is this mod issue?

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#21]
dankstorage can't set frequency or unlock frequency even using command to unlock frequency it comback invalid id is this mod issue?

**Comment by MindBrain27** [comment]
Ok this took some messing around with.

A, the commands to set frequencies have been removed but may come back apparently, https://github.com/Tfarcenim/Dank-Storage/issues/219.
There is only a command to reset the frequency right now.

B, There is a hidden text field when you have the Dank open that you can select and type the frequency in.
![image](https://github.com/MindBrain27/Sky-Greg/assets/74363414/d3907c96-4a18-48ad-a96e-c6ec05fa37a9)
Just make sure you unlock the frequency (with the O or X button) and save it after you set it (with the S button).

**Comment by MindBrain27** [comment]
The Red Print seems to copy frequencies if a Dank is in a Dock, however I can't seem to figure out how to paste the frequency onto another Dank, manually typing the frequency in seems to be the way to go.

**Comment by akasia** [comment]
i get it that next to sort button not key bind  so confuse how to use lock or unlock  frequency

**Comment by akasia** [comment]
thx ~~

**Comment by MindBrain27** [comment]
I added some quest text explaining this bit as well.

**Comment by akasia** [comment]
nice tq
