### ISSUE TITLE
How to get clay

### ISSUE THREAD

**Issue by makamo** [MindBrain27/Sky-Greg#22]
Hello 

How do I get clay at the beginning to make bricks?

**Comment by MindBrain27** [comment]
1, You can use a Dust block that you can obtain by using the crushing hammers on Sand (the Netherite Hammer from the Item Frame), and you can use a Dust block on the Primitive Water Condenser (that starts on the platform, the block with the Water Bucket) to get a Clay block.

2, You can use any of the stone dust variants you get from mining ores on the Primitive Water Condenser to get Clay Balls.

**Comment by makamo** [comment]
Thanks for fast response.

**Comment by MindBrain27** [comment]
No problem! Slightly later on you can also use the Infinite Block Generator to generate infinite Terracotta and Macerate it into Clay Dust too. Same for Concrete.
