### ISSUE TITLE
is any 1 ae2 patten encode issue with enconde processing petten did;t work need menuel place item to make it happen

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#24]

**Comment by MindBrain27** [comment]
I noticed some processing patterns don't autofill the items from REI, I don't know if that's an issue on REI, AE2, or GregTech's side. Crafting patterns work fine but processing patterns only work sometimes.

**Comment by akasia** [comment]
yup ~

**Comment by akasia** [comment]
hmm omost every patten can't encod it just put fluid in but item not
try encod piston just come with fluid zzz
![2024-01-09_13 38 35](https://github.com/MindBrain27/Sky-Greg/assets/14824981/b40bccc1-0f3a-4e1a-825e-5c67a4e7e3bc)

**Comment by MindBrain27** [comment]
A tip to help with this:

Sort Inventory hotkey and the set crafting amount (AE2) hotkey are the same by default (middle click) and the Sort Inventory one overrides the AE2 one. Change the Sort Inventory hotkey to something else so nothing conflicts with the AE2 hotkey. 

Drag items and fluids in from REI and set the amount with the AE2 hotkey (middle click).

If you need 144 mb of a fluid you can type 0.144 for the amount of buckets.

Hope this makes sense and helps. It's annoying but it works for now.

**Comment by akasia** [comment]
emmm batter than none

**Comment by MindBrain27** [comment]
Turns out you can actually drag right from the REI recipe pin. Pin the entire recipe to the side the n just drag what you need over. Works for items and fluids and is definitely better than the previous method I mentioned.

![2024-01-16_08 20 12](https://github.com/MindBrain27/Sky-Greg/assets/74363414/5d2ed89e-adda-4460-8109-b279170ace2a)

**Comment by MindBrain27** [comment]
So this in an REI issue. I will be switching back to JEI either next update or the update after as there is some scripting to change on my side.

**Comment by MindBrain27** [comment]
finally fixed
