### ISSUE TITLE
graphi issue GT blastfurnace working but did't glow ~~

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#27]
graphi issue GT blastfurnace working but did't glow ~~
shader on

![2024-01-08_07 54 41](https://github.com/MindBrain27/Sky-Greg/assets/14824981/99e66632-ab2b-4b7b-b88d-1d848ce2fad7)
shader off

![2024-01-08_07 57 16](https://github.com/MindBrain27/Sky-Greg/assets/14824981/85ef31ac-501f-46d5-a5ac-c47168356acb)

**Comment by MindBrain27** [comment]
Still the same issue if you reload textures with F3+T? I have not seen that yet but I also have not shared walls with them before either.

**Comment by MindBrain27** [comment]
you may need to do F3+T twice, it may help, it may not.

**Comment by akasia** [comment]
nop still same didt glow

**Comment by akasia** [comment]
zzz random relog fix that issue

**Comment by MindBrain27** [comment]
I've noticed a few texture issues from time to time with certain GT blocks, usually a relog or F3+T works for them. I am going to close this for now.
