### ISSUE TITLE
GT cable conection question

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#31]
is GT cable got conection limit?8A with 8 generator?

**Comment by MindBrain27** [comment]
I'm pretty sure you can just stack generators, I would need to test a bit later on but I did have 2 Steam Turbines both on the same Cable line leading to a few machines that did work (as long as your Cables have enough amps).

If stacking generators on the same Cable line into machines doesn't work then you would need a Battery Box with filled Batteries, which can definitely have multiple generators feeding energy through a single Cable line.

**Comment by akasia** [comment]
yes i feed it in battery box 4x but can't keep up with 25  machines it just burn cable i using lv 4xsuperconductor on output

**Comment by akasia** [comment]
after i change it to 8xbattery and 8x cable than it ok

**Comment by akasia** [comment]
and 1 more thing can make superconductor wire abit cheap?

**Comment by DEMAXGAMER195** [comment]
The voltage tells you how much power it can supply (eg. a 32V wire will burn above 32V) and the amps tell you how many machines it can power at the same time if they run at given max voltage (If you have wires that can sustain 4 Amps and you try to force 5 Amps to 5 machines running at 32V they will burn up.) 
If you limit the power that is provided (in my example to 4 Amps) you can however run more than 4 machines at less then 32V. 
Try to only supply as much power as your weakest part of the network can handle.

**Comment by MindBrain27** [comment]
^^ They have a pretty good explanation, if you have 8 machines asking for power at the same time, that's 8 amps so you need an 8x buffer and 8x Cables to match. And no I don't think I'm going to be making any existing GT recipes cheaper for now at least, maybe if more people request but I've tried to leave GT recipes as they are for the most part.
