### ISSUE TITLE
I think i found dube bug maybe?

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#34]
using item scroll down to inventory on item filter can dupe item or del item

**Comment by akasia** [comment]
hold ctrl with lef click and right click olso work?><

**Comment by MindBrain27** [comment]
I've been trying to do this but can't replicate it, does it have any filters set? is it from a machine or chest? is it within your inventory? is it only the item filter? does it happen if you relog?

**Comment by akasia** [comment]
er try crate with robotic arm with filter exact  mode othe i will try when i come back gtg

**Comment by akasia** [comment]
![2024-01-16_12 40 39](https://github.com/MindBrain27/Sky-Greg/assets/14824981/d08833b2-82eb-49ee-b385-368f8972a47f)
![2024-01-16_12 40 40](https://github.com/MindBrain27/Sky-Greg/assets/14824981/4106dd04-accb-4e11-87c5-84789fe46fa0)
![2024-01-16_12 40 44](https://github.com/MindBrain27/Sky-Greg/assets/14824981/5c427bb2-f13e-4923-bb8b-500ac4a41000)
![2024-01-16_12 40 47](https://github.com/MindBrain27/Sky-Greg/assets/14824981/4341b1d3-26c0-44ba-950c-ef0fba0c446d)
![2024-01-16_12 40 50](https://github.com/MindBrain27/Sky-Greg/assets/14824981/a8fcdb2c-d321-4de2-8f3d-bc259aefd085)
this right click increace amount left click dicreace amount that normal but if click with crtl it wheb decreace will drop item in invontory

**Comment by akasia** [comment]
inventory essentials one option transfer one  issue mayb  cos i change that tranfer one ky bind that that did't happen agian my crtl key bind with 
but mouse scroll still can push item in to filter or (out from filter) an in inventory still can dupe it
![2024-01-16_12 56 42](https://github.com/MindBrain27/Sky-Greg/assets/14824981/dec115cc-c667-4162-998d-5f49ce294aef)

**Comment by MindBrain27** [comment]
Wow ok yeah that's definitely a dupe bug. I'm going to make an issue on the GT GitHub for it.

**Comment by MindBrain27** [comment]
https://github.com/GregTechCEu/GregTech-Modern/issues/760

**Comment by akasia** [comment]
it working?

**Comment by MindBrain27** [comment]
Yeah I was able to dupe anything with Robot Arms and Conveyors with Item Filters by mouse wheel scrolling, also void/delete items by scrolling the other way. I didn't actually try the control click method though.

**Comment by akasia** [comment]
yup new update still not yet fix this issue
