### ISSUE TITLE
Looking For Mod

### ISSUE THREAD

**Issue by MindBrain27** [MindBrain27/Sky-Greg#35]
I'm looking for a mod that allows you to capture a mob, like the Mob Imprisonment Tool from Industrial Foregoing. Ideally a standalone mod with just that or not too many other features.

**Comment by Cassa-sys** [comment]
You could re-enable the Soul vial from EnderIO. Would likely have to alter some recipes. Alternatively there is [Mob Capturing Tools](https://www.curseforge.com/minecraft/mc-mods/mob-capturing-tool/), or [Mob Lassos](https://www.curseforge.com/minecraft/mc-mods/mob-lassos).

**Comment by MindBrain27** [comment]
Lol i forgot about the Soul Vials, Soul Vials are coming back then. Thank you!
