### ISSUE TITLE
Basic Tools Quest

### ISSUE THREAD

**Issue by Atarnator** [MindBrain27/Sky-Greg#38]
Hi,

I just noticed that in the newest version 1.13 the tools wanted by the quest got replaced by logic filters from mod Item filters.
The tags looks fine but it doesn´t recognize the tools crafted.

![Greg sky](https://github.com/MindBrain27/Sky-Greg/assets/153952053/ebe15004-88bd-4881-91f4-6367cfec4be8)

**Comment by MindBrain27** [comment]
Interesting, I'm working on that now. It seems to be the recent FTB Quest update, it's not looking at tags properly anymore, I'll have to downgrade that if they don't release a fix soon. I just no longer have an option to mark an item as a tag within the quest editor anymore.

**Comment by Atarnator** [comment]
Also the quest right beside it with hopper botany pots. Same problem. Just so you know ;)

**Comment by MindBrain27** [comment]
Ah perfect thank you I was trying to think of more quests with tags, there shouldn't be too many more if any. I'll probably just downgrade quests later tonight.
