### ISSUE TITLE
Treated wood frames visual

### ISSUE THREAD

**Issue by Atarnator** [MindBrain27/Sky-Greg#39]
Also something a bit different, are the treated wood frames supposed to be see through? I suppose it is a bug of the mod or maybe shaders?

![Greg sky 2](https://github.com/MindBrain27/Sky-Greg/assets/153952053/3030b65d-2089-4362-bdad-346430d22701)

**Comment by MindBrain27** [comment]
My first guess would be shaders, if you toggle shaders off and reload the world I'm guessing it would be normal. On that note shaders also make it so you can't see the connecting lines between Laser Nodes for LaserIO. I haven't found a shader pack that works with LaserIO yet.

**Comment by Atarnator** [comment]
Tried to turn off the shaders but that didn´t solve the problem. I think it has to do something with connecting with the blocks that are below it. Because when i put it in air so the block floated it looked completly normal, but once you put something under it, it disapears.

**Comment by MindBrain27** [comment]
Yeah I just tested no shaders and reloading world and same thing, kooks like issue with GT. I don't remember seeing that before though I think a recent update did that.

**Comment by Cassa-sys** [comment]
Can confirm this has only started occurring with a recent update. Was not an issue in 1.09. Must have been some GregTech update since then. 


> On that note shaders also make it so you can't see the connecting lines between Laser Nodes for LaserIO. I haven't found a shader pack that works with LaserIO yet.

Complementary Shaders work if you disable bloom. Otherwise they have this blinding green light.

**Comment by MindBrain27** [comment]
Fixed with recent GT update.
