### ISSUE TITLE
why greg fluid pipe can't set  direction steam flow so Awkward can't provie enough to far side

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#4]
why greg fluid pipe can't set  direction steam flow so Awkward can't provie enough to far side

**Comment by MindBrain27** [comment]
I don't quite understand that, but if you're having troubles with GregTech pipes there are a few issues with them currently, LaserIO was added to combat that for now until pipes work properly.

If you just need to attach pipes together or dictate where they go then use a Wrench.

Hope this helps. Let me know.

**Comment by akasia** [comment]
gt pipe so bed tranfer rate so low even with gold large pipe bronze boiler pordus 
i try run 8 bronze boiler wtith 3 machine still cant get enough steam flow in zzz

**Comment by akasia** [comment]
zzz boiler produce 6l/t but the bast pipe can use is tranf rate b4 steel is only 600mb/t zzz and huge steel pipe only 1800mb/t
1000mb=1L right?

**Comment by MindBrain27** [comment]
In their case actually 1L = 1mb, I don't know why it's written like that. A Normal Bronze Fluid Pipe can candle 36mb/t, that can run 6 machines running at 6L/t.

1L-1mb.

A Normal Bronze Fluid Pipe should be more than enough for any basic early game setup. As seen in the following picture are Normal Bronze Fluid Pipes running 2 steam powered Furnaces and a steam powered Alloy Furnace.

![2023-12-26_01 11 13](https://github.com/MindBrain27/Sky-Greg/assets/74363414/194edea8-b5ad-4451-b209-c607912ee9e6)

**Comment by akasia** [comment]
but my case is 8 boiler can't keep 2 meching idle 3 meching running
1 steam extractor 1L/t
1 steam macerator ideling
1 steam forge hammer 8L/t
1 alloy smelter 8L/t
1 steam compresser 1L/t
 total 18L/t

8 bronze boiler 6L/t *8 48L/t 


![2023-12-26_20 45 09](https://github.com/MindBrain27/Sky-Greg/assets/14824981/53addc3a-7a03-4373-b184-00f199460b71)
![2023-12-26_20 47 57](https://github.com/MindBrain27/Sky-Greg/assets/14824981/26eecd55-6169-4819-a55d-16f57e2f56b3)
![2023-12-26_20 50 54](https://github.com/MindBrain27/Sky-Greg/assets/14824981/707bd79d-3fec-4afa-97d4-e3187ddf8a46)
![2023-12-26_20 54 29](https://github.com/MindBrain27/Sky-Greg/assets/14824981/41ff8e00-a256-4a31-92dc-1cb2a5d6e1a0)
![2023-12-26_20 45 04](https://github.com/MindBrain27/Sky-Greg/assets/14824981/0dcac32f-4e66-47de-b0c9-a5f678c4a780)

![2023-12-26_20 58 37](https://github.com/MindBrain27/Sky-Greg/assets/14824981/be548aa3-815d-48e0-9b4c-f83008e312ec)
 steam still can't keep up

**Comment by akasia** [comment]
zz so wanky bronze barrel don't auto output from bottom?
![2023-12-26_21 12 12](https://github.com/MindBrain27/Sky-Greg/assets/14824981/038a071b-a7a9-48a5-b8e1-e62e415bb741)
![2023-12-26_21 12 30](https://github.com/MindBrain27/Sky-Greg/assets/14824981/3db33834-9420-407a-bc7d-5d779261aab5)
barrel is full

**Comment by akasia** [comment]
has no choise gotto rush laser io

**Comment by MindBrain27** [comment]
I see 2 issues here, an open pipe can let steam escape, in your 5th picture behind the top right chest there is an open pipe connection and inbetween the two hoppers in the same picture there in a pipe that is not connected to the other pipe beside it.

Drums will auto export out the bottom if you use a Screwdriver on the Drum.

**Comment by MindBrain27** [comment]
Also FYI, I added LaserIO as a different piping method, but EnderIO conduits will also be available later today.

**Comment by akasia** [comment]
that 1 i olso thought so but after i fix still the same >.<
i has to tempo set up like this even with 2 boiler with 1 alloy alloysmelter still show steam ca't keep have to sprare pipe connaction up still is the pipe iusse 
![2023-12-26_21 41 18](https://github.com/MindBrain27/Sky-Greg/assets/14824981/67de1ebc-7fbb-4acd-b532-e33b430d8510)
lasserIO is better plss don't remove it

**Comment by MindBrain27** [comment]
Wont be removing, there will be both
