### ISSUE TITLE
Modular routers

### ISSUE THREAD

**Issue by Atarnator** [MindBrain27/Sky-Greg#40]
Hello,

I don´t remember perfectly but few days ago I made a little setup with modular routers for breaking ores, but suddenly it stoped working. Routers with breaking module now don´t break any blocks not even cobblestone. I didn´t see anything about that in changelog so I guess the update of the mod is causing it.

**Comment by MindBrain27** [comment]
Off the top of my head are you in a recently claimed chunk? Some machines that break blocks do not work in claimed chunks.

**Comment by Atarnator** [comment]
I´ll be damned, okay, thank you

**Comment by MindBrain27** [comment]
I remember this with Industrial Foregoing in another pack. The game things it's griefing, ill see if I can mess around with whitelists and make it work.

**Comment by akasia** [comment]
if claimd chunk need to setting allow fate player to make it work
dude just notice were is claim chunk icon go

**Comment by MindBrain27** [comment]
I believe I fixed this for next update, changed the FTB Chunks config for fake players from "check" to "allow".

**Comment by MindBrain27** [comment]
I forgot this in the update just posted, this will be next update now, but you can change the server configs in your world save folder for ftbchunks to allow for now if you wish.

**Comment by MindBrain27** [comment]
This has been changed but I'm not sure if that config setting is applied to existing worlds for other people. If it's still an issue you will need to go in and change the config. The update may only apply to new worlds being created.
