### ISSUE TITLE
No maintenance issues displayed

### ISSUE THREAD

**Issue by DreeperteGit** [MindBrain27/Sky-Greg#41]
I don't know if it is intended or not but the EBF don't show the maintenance issues

**Comment by MindBrain27** [comment]
In the controller block or in the Maintenance Hatch?

**Comment by DreeperteGit** [comment]
In the controller block (the EBF block)

**Comment by MindBrain27** [comment]
It shows in the Maintenance Hatch only (in this version at least). A little icon to the top right of the GUI for the Maintenance Hatch. I have yet to mess around with a Maintenance Detector, not sure how it works but it looks like a Cover.

**Comment by DreeperteGit** [comment]
okay thanks !
