### ISSUE TITLE
Laser IO

### ISSUE THREAD

**Issue by Atarnator** [MindBrain27/Sky-Greg#43]
So I have ran into a problem where when I want to link 2 Laser nodes together it doesn´t connect. I can select the node but no matter how I click second node it doesn´t form the laser connection. At first I thought that it is shader bug again, but connecting to machines with cards works so I guess something wrong with the wrench or smth.

**Comment by MindBrain27** [comment]
If you put a Laser Connector between as a relay does it work? Can't test right now.

**Comment by Atarnator** [comment]
Nope, can´t link anything

**Comment by MindBrain27** [comment]
And does reloading the world do anything?

**Comment by Atarnator** [comment]
Nah, nothing.

**Comment by MindBrain27** [comment]
I know shaders make thr connection line invisible (still works but the red line doesn't appear) and without turning off bloom there is a massive green glow, but other than those 2 I haven't had any issues with LaserIO and I have them everywhere.

**Comment by Atarnator** [comment]
Oh, yea. I read about the glow but that red line was really invisible due to shaders again, i will try to look into it if I can find something that causes it.

**Comment by MindBrain27** [comment]
I just tested and had no issues connecting any Nodes together, not sure what's going on.

![2024-01-21_14 00 16](https://github.com/MindBrain27/Sky-Greg/assets/74363414/c9bb5bfc-6e11-4255-8712-215bc3563fc4)

I know it sounds weird but maybe try a new Laser Wrench? Maybe it has a weird nbt that is messing with things.

**Comment by MindBrain27** [comment]
If turn on advanced tooltips with F3+H you can see the nbt on items, just a thought.

**Comment by Atarnator** [comment]
No it were the shaders 100% I tried to find something about it and discovered when you set the node red color to value between 30 to 230 the connections suddenly show up even with shaders.

**Comment by MindBrain27** [comment]
Oh that's helpful to know actually that works quite well.

**Comment by Atarnator** [comment]
This is when the color is set in between:
![Greg sky 3](https://github.com/MindBrain27/Sky-Greg/assets/153952053/66a9bac9-c134-4d39-b2ca-527321364c23)
![Greg sky 2](https://github.com/MindBrain27/Sky-Greg/assets/153952053/5d53e1bb-1cde-460d-a864-ca69ef19fa2a)

And this is when you crank it up above 239:
![Greg sky 4](https://github.com/MindBrain27/Sky-Greg/assets/153952053/06e896b3-8bd3-4cc4-a53f-bc9924c11035)

**Comment by MindBrain27** [comment]
That's an odd one but it works lol. So your stuff is working now right?

**Comment by Atarnator** [comment]
Yes, it works now just fine. It´s a shame that the shaders cause that much trouble because how they work with the light is really great and I want to play with them.

Anyways thank you for the help again.

**Comment by MindBrain27** [comment]
No problem! I hate how much shaders mess with LaserIO, it's annoying, but I'm going to close this for now, glhf.
