### ISSUE TITLE
REI causing a Freeze when joining a server on Sky Greg

### ISSUE THREAD

**Issue by Storyboard-MC** [MindBrain27/Sky-Greg#44]
I am not sure of what is causing the issue but when I login to my server it start freezing like crazy but when I kill the process restart the pack and join a single player world before joining the server the freeze doesn't happen.

**Comment by MindBrain27** [comment]
Does it happen if you change the skyblock world type to Default? The one without all the stuff on it.

**Comment by MindBrain27** [comment]
the pack has switched from REI to JEI. REI is no longer present. Feel free to open another one if JEI or something else is causing it.
