### ISSUE TITLE
Batteries in buffers

### ISSUE THREAD

**Issue by Atarnator** [MindBrain27/Sky-Greg#45]
Hey,

I just upgraded my battery buffer to 16x and noticed when you have 0 charge or completly full charge on batteries (LV currently) you can stack them inside the machine. So realisticaly I can fill it with 64 x 16 LV batteries, which I don´t think it is supposed to do.

Stacking them in my inventory is great because it doesn´t fills your entire inventory but maybe try to point this out on GT github so they can limit the buffer slot to 1 battery.

**Comment by MindBrain27** [comment]
IIRC they stack if they are empty but they will not accept or expel a charge if they are stacked (I could be wrong). I think this even happened in 1.12. I would have to test a bit but I think I remember it working like this in Omnifactory too. I will play around with after work.

**Comment by Atarnator** [comment]
![Snímek obrazovky 2024-01-22 181641](https://github.com/MindBrain27/Sky-Greg/assets/153952053/5e9d2bf9-d926-44e6-ac0c-7befead2eb05)

**Comment by Atarnator** [comment]
Ah okay I tested it now but when they are stacked they can´t discharge at the same time so you have to spread them.

It´s okay then, you can close the case.

**Comment by Atarnator** [comment]
> IIRC they stack if they are empty but they will not accept or expel a charge if they are stacked (I could be wrong). I think this even happened in 1.12. I would have to test a bit but I think I remember it working like this in Omnifactory too. I will play around with after work.

You are right. I should have check it first and then write to you.

**Comment by MindBrain27** [comment]
No problem, I found it strange that they stack inside the Battery Buffers in the first place.
