### ISSUE TITLE
is large steam boiler muffler hatch can't extract on any form?

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#5]
is large steam boiler muffler hatch can't extrac on any form?
i try with hopper and steel crate with conver belt and robotic arm olso cant extract is this normal?

**Comment by MindBrain27** [comment]
I noticed this but I also noticed no effect when the Muffler Hatch was full, I believe this is an internal bug for now. Maintenance Hatches seem to only ever need to be done once and never again as well. Th Maintenance and Muffler hatches seem to be working but not working as intended for now. I may disable Maintenance but I don't know if that will disable Mufflers as well.

I literally have 3 Large Bronze Boilers and an EBF running with full Muffler Hatches currently.

Been keeping an eye on it, not sure if disabling maintenance is the way to go or just waiting to see a fix.

**Comment by akasia** [comment]
hmm ok
