### ISSUE TITLE
large bronze boiler not starting

### ISSUE THREAD

**Issue by Sebewe** [MindBrain27/Sky-Greg#55]
For some reason the 4th large bronze boiler in my world wont start up. It's not crossing chunk borders, you can right click the controller and it doesnt say anything is wrong with the multiblock, it has both fuel and water, the maintenance hatch does not say there are any problems, Ive tried rebuilding it and moving it around and it wont start, I've tried restarting my game, I'm not sure what else to do. The fuel is heavy oil and I have 3 other large bronze boilers running on it with the same setup and they are working fine. The multiblock was working fine before but once I set up the fourth boiler above it, it shut down. The boilers are separated by a layer of bronze frames.

![Untitled](https://github.com/MindBrain27/Sky-Greg/assets/38896608/b21e15d6-606d-4a66-8693-48f6f92ad474)

**Comment by DEMAXGAMER195** [comment]
The single torch next to the muffler hatch is enough to stop the structure from processing.
It's kinda stupid, but just never place anything in front of them, not even small things like torches.

**Comment by MindBrain27** [comment]
Yeah everything looks in order except for that 1 Torch. If it doesn't run after removing the Torch try flicking it off and on with the power switch in the GUI, it may need an update.

**Comment by Sebewe** [comment]
Yep, that fixed it lol. Thanks!
