### ISSUE TITLE
My world got corrupted since 1.17 update

### ISSUE THREAD

**Issue by SkyrixR** [MindBrain27/Sky-Greg#58]
Idk whats wrong, something is corrupted and tbh I don´t have the enough time to check my base because I start moving and 20sec after is already crashed :(

![imagen_2024-02-07_171854599](https://github.com/MindBrain27/Sky-Greg/assets/157075330/7fcb6f11-c558-4c42-9474-cdb117a88148)

Gives me the classic error -1 code (Im spanish), and I really don´t know what is corrupting my game, maybe the pipes or the overload of machines (Lava Furnaces), if anyone can help me in this, I just got to HV and the fun part starts here :/

P.D: My pc can´t handle shaders so I uninstall every1 of them, maybe that is the problem?; who knows...

**Comment by SkyrixR** [comment]
Ill update to 1.18 and check out if still happens

**Comment by MindBrain27** [comment]
try going back to the 1.16 version actually

**Comment by MindBrain27** [comment]
I haven't had anything else like this pop up but I feel it may have to do with the GregTech pipes.

**Comment by SkyrixR** [comment]
I found something maybe useful, let me take a picture and explain

**Comment by SkyrixR** [comment]
Okay, here comes the order.

At first EMI is delaying to load, as it seems in the picture
![Captura de pantalla 2024-02-07 173035](https://github.com/MindBrain27/Sky-Greg/assets/157075330/096d480a-3d4c-4c45-9527-acb483071137)

I took another picture of the mod loading (including gtceu) and still delaying. (I mean by including gtceu because it was reloading it)
![Captura de pantalla 2024-02-07 173124](https://github.com/MindBrain27/Sky-Greg/assets/157075330/4497e335-06f7-4dc1-b776-9eb5e48f13ec)

When it loads it shows the next thing 
![Captura de pantalla 2024-02-07 173155](https://github.com/MindBrain27/Sky-Greg/assets/157075330/3c9361b0-a180-4504-ad37-889a5a771888)

And going into the errors it shows this
![Captura de pantalla 2024-02-07 173217](https://github.com/MindBrain27/Sky-Greg/assets/157075330/32937e3f-530d-4e74-80cc-3c2d7b2d5c1e)

2 minutes after that, the game crashed.

Idk if haves something to do, ill check whats up with 1.16 version to see if its my world or something just went wrong during the coding :D

PD: This is 1.18 update.

**Comment by SkyrixR** [comment]
1.16 (no errors)
![imagen_2024-02-07_174324785](https://github.com/MindBrain27/Sky-Greg/assets/157075330/8bce5a6d-879a-4ca4-b2f4-dab6f6a7667e)

**Comment by MindBrain27** [comment]
1.16 introduced a restructure of how GT pipes work, if you heavily use GT pipes it may be because of that

**Comment by MindBrain27** [comment]
" remade how pipes are implemented
WARNING: YOU MAY NEED TO REBUILD YOUR PIPE NETWORKS"

that was in the changelog for GT for the 1.16 modpack version

**Comment by SkyrixR** [comment]
I rebuild every single pipe network on the base, redo my Diesel section and etc etc. It crashed again in 1.16

**Comment by SkyrixR** [comment]
Ill just change to 1.15 and see if it is my world or not.

**Comment by MindBrain27** [comment]
if it still crashes on 1.16 version my guess is pipes, if still crashing try 1.15

**Comment by MindBrain27** [comment]
hopefully 1.15 works, if it does then it is definitely the pipes

**Comment by SkyrixR** [comment]
And if it is the pipes, im just stuck at 1.15? :(

**Comment by MindBrain27** [comment]
no if its the pipes then my suggestion (still sucks to do) is maybe get rid of the pipes before updating the pack, i just want to see if its the pipe issue, so far you're the first with any pack update crashes though

**Comment by MindBrain27** [comment]
if it crashes again on 1.15 do a pastebin link for the crashlog and ill see

**Comment by SkyrixR** [comment]
It is the pipes, ill do a completely removal of pipes of my entire base and update to 1.18, ggs my Diesel

**Comment by MindBrain27** [comment]
unfortunate, i wouldnt have expected a complete pipe overhaul, kinda hard to avoid unfortunately, make sure to check out the GT changelogs, i post them with any pack update i do

**Comment by MindBrain27** [comment]
remember there are automatic world backups as well if things turn into an issue later on

**Comment by SkyrixR** [comment]
Im a noob at Gregtech so maybe the overhaul of pipes is that XDDD

**Comment by MindBrain27** [comment]
well its a great place to learn GT!

**Comment by SkyrixR** [comment]
I confirm it was the pipes, everything normal now XD

**Comment by MindBrain27** [comment]
good to hear! i'll close this for now, feel free to open something else if anything comes up!

**Comment by SkyrixR** [comment]
had to start from 0, all my diesel buffer went gone, gg´s !
