### ISSUE TITLE
Upgrading from version 1.15 to 1.19 crashes on boot.

### ISSUE THREAD

**Issue by Severe1** [MindBrain27/Sky-Greg#59]
[crash-2024-02-01_08.31.34-client.txt](https://github.com/MindBrain27/Sky-Greg/files/14205781/crash-2024-02-01_08.31.34-client.txt)

Have been playing on version 1.15 for a couple of days. Got fed up with the REI AE2 Bug so decided to want to upgrade. However when I just booted the pack it would crash with a "No SLF4j providers were found" stack-trace.

**Comment by Severe1** [comment]
I have tried removing all pipes from my world, however it did not fix this issue. Cables should still be ok right?

**Comment by MindBrain27** [comment]
If you go back to 1.15 does it work properly? I had 1 other case like this and they had to go back to 1.15, remove the piping, then update to newer version and it worked for them. It's mot am ideal solution but it did work for them. I'm just guessing it's due yo the piping like the other person.

**Comment by Severe1** [comment]
I have gone back to 1.15, which works, remove the piping and upgrade to 1.19 (or 1.16 for that matter) and the issue remains.

**Comment by MindBrain27** [comment]
1.16 gives the same crash or different crash?

**Comment by MindBrain27** [comment]
the original crash report is going on about REI but with 1.16 REI should be removed so it should be something different

**Comment by Severe1** [comment]
[-1707389725529.log](https://github.com/MindBrain27/Sky-Greg/files/14208124/-1707389725529.log)
[-1707389909119.log](https://github.com/MindBrain27/Sky-Greg/files/14208126/-1707389909119.log)

It crashes on 1.16 still.

**Comment by Severe1** [comment]
FYI, fresh installations seem to work. In a bit I'll try and paste my world over and see if it breaks again.

Edit: Pasting my save did work.
