### ISSUE TITLE
Modpack

### ISSUE THREAD

**Issue by TheGCrew2Alt** [MindBrain27/Sky-Greg#6]
Hello My name is TheGCrew2 and i will be looking into your pack on live. If you see this message soon go to https://www.twitch.tv/TheGCrew2 . or just message me. i will send a video here soon to show you what i think you should do.

**Comment by MindBrain27** [comment]
I don't understand this but if you're just advertising a twitch channel that plays Among Us then i don't really care. If you have suggestions feel free to leave them but not in video form.
