### ISSUE TITLE
Ethanol

### ISSUE THREAD

**Issue by gotoxy** [MindBrain27/Sky-Greg#63]
Im trying to make ethanol but the recipe doesn't seems to work.

I use a Programm Circuit on #1 and i put 1bucket of biomass in a basic distillery and it does nothing.

I tried at fist doing the biomass from (Plant ball -> Bio Chaff+ Water in Basic Brewery) not working

ive read somewhere you need distilled water, so i tried but the recipe doesn't work in the distillery (Bio Chaff + dis.wat.)

So i made some biomass from sugar cane + water in distillery but again, not luck that biomass does work for doing ethanol.

Im out of idea.

**Comment by MindBrain27** [comment]
Are you on the newest version of the pack? There was a recent pack version that had some recipes bugged out and not working.

**Comment by gotoxy** [comment]
Seems i am, it says version Sky Greg 1.20 (Current)

**Comment by MindBrain27** [comment]
Ah, it needs an Advanced Distillery (MV) as the recipe requires 100 EU/t

**Comment by MindBrain27** [comment]
For the Biomass -> Distillery recipe at least.

**Comment by gotoxy** [comment]
i see, thats the part i havent understood. Ill keep that in mind that those stuff are EU restricted. Saddly that kill my plan on making a super tank lol. Thx tho

**Comment by gotoxy** [comment]
a button is hiding the (MV) in REI.

**Comment by gotoxy** [comment]
ty
