### ISSUE TITLE
KubeJS startup script errors when launching version 1.21

### ISSUE THREAD

**Issue by Kanton99** [MindBrain27/Sky-Greg#64]
When starting the modpack in with the 1.21 version KubeJS finds duplicate keys for 'gtceu:glass_box' in the registry 'gtceu:recipe_type' and in the 'gtceu:machine' registry. 
startup.log is attached
[startup.log](https://github.com/MindBrain27/Sky-Greg/files/14358944/startup.log)

**Comment by MindBrain27** [comment]
2 things for this, you can either probably just reinstall the modpack, or navigate to the kubejs folder within the modpack and check in the startip_scripts folder, there should only be 1 file in that folder named CUSTOM MULTIBLOCKS, if a file named example is in there as well, delete the example file. It looks like you have 2 in that folder.

**Comment by clavierp** [comment]
Same error here, resolved by removing example.js in kubejs/startup_scripts

**Comment by MindBrain27** [comment]
So this seems to happen if using certain launchers I've noticed, but the above fix works. Some launchers seem to treat the changed file name as a new file instead of changing the original.
