### ISSUE TITLE
(Not working) MV Macerator Boron recipe not working.

### ISSUE THREAD

**Issue by wwwname** [MindBrain27/Sky-Greg#66]
MV Macerator Boron recipe not giving Boron dust from Refined Lepedolite Ore. It shown chance to get Boron Dust should be 14% +8.5% tier. But after 150 ores i got 0, it's quite low chance to get 0 from 150 tries with 24%. Less then 0.01%.
After finding bug I tested HV and IV machines and they work as intended.
Such recipes should work staring from LV.

**Comment by MindBrain27** [comment]
This is actually just a confusing mess with GT and JEI. Macerators are not supposed to give bonus outputs until HV, with the chance of a bonus increasing each tier above HV. I have just recently added quest notes and tooltips on lower tier macerators explaining this which will be in the next pack update.

**Comment by wwwname** [comment]
I see, it mostly number of output slots in macerators to blame, for example in gt new horizons there only 1 slot until hv.
