### ISSUE TITLE
筛网为什么会消失

### ISSUE THREAD

**Issue by icegrassdream** [MindBrain27/Sky-Greg#67]
机器里面的筛网总是消失是设定还是BUG？

**Comment by MindBrain27** [comment]
show picture? i am not sure what you are talking about but it sounds like a bug

**Comment by icegrassdream** [comment]
在使用蒸汽筛选机的时候，筛选机里面的筛网会消失，机器停止工作；没有截图，因为截图不能展示消失的过程；
目前我使用的高压蒸汽筛选机，在使用铁制筛网筛选燧石、钢制筛网筛选粉碎下界岩的时候筛网会消失，机器停止工作；
其他的筛选器和筛网还没有制作出来，没有测试；
