### ISSUE TITLE
Issue or gregtech?

### ISSUE THREAD

**Issue by RandAlThorn** [MindBrain27/Sky-Greg#68]
I just recently started playing this mod pack and i am really enjoying it and greg tech is rather new for me. I have figured out the LV and MV machines and gotten them to work just fine with the different recipes but i occasionally come across a recipe that doesn't work despite the recipe saying it should go into an LV machine or MV. And the occasional ULV just confuses me but that's more of a getting to know greg tech issue on my end.

Example of issue: Trying to make cupronickel coil block in an LV basic assembler. it doesn't work. I tried it in an MV advanced assembler. Same issue. When i have come across this issue before it either is an LV vs MV issue or there is a work around by crafting it "by automated crafting table" but there is no alternative way to make this.

**Comment by RandAlThorn** [comment]
not sure why but reloaded the game and its working now. Guess ill add that to my list of ways to fix issues, lol

**Comment by MindBrain27** [comment]
Honestly sometimes GregTech just derps, if you are sure it's the right
recipe and it's not working try taking the items out and putting them back
in and it sometimes fixes it but a relog would also do it. GregTech
sometimes just bugs out and you need to refresh the machine/inputs but not
often.
