### ISSUE TITLE
Missing Patterns for REI

### ISSUE THREAD

**Issue by TheMilso** [MindBrain27/Sky-Greg#7]
I am unable to crate Cobalt Brass to make the LV Cutter.
there are varies other patters i have notices are missing as well.

Playing on 1.0.6

**Comment by MindBrain27** [comment]
There are some recipes weirdly being hidden in REI, the recipes still work but are just hidden for some reason, I have been re adding the recipes for the ones I find, I'll re add this one so it shows, but if you throw 7 Brass Dust, 1 Aluminium Dust, and 1 Cobalt Dust in a Mixer with a Circuit 1 it will craft.

What other recipes did you notice? I found a handful of Mixer recipes missing.

**Comment by MindBrain27** [comment]
If you run into more Mixer recipes like this before I fix them which you probably will, you can check the uses for the ouput, in this case the Aluminium Brass Dust, see the Centrifuge recipe to see the mixture of dusts required. Tell me any others you notice and I'll fix them all though.

**Comment by TheMilso** [comment]
I notice the glow stone one is also missing.

**Comment by TheMilso** [comment]
also the AE2 silicon press is missing the pattern.

**Comment by MindBrain27** [comment]
> I notice the glow stone one is also missing.

![2024-01-01_08 15 04](https://github.com/MindBrain27/Sky-Greg/assets/74363414/cfbdae74-9923-490f-b58d-42b40e8bcd4b)

This should cover the Glowstone but this should already be in there for you, the Silicon Press I just fixed. FYI its just Silicon from AE2 following the same pattern as the others. Will have a small update later on today.

**Comment by TheMilso** [comment]
First Thanks for the fast response.
The Silicon Press i figured out as it lined up with the other ones.

just FYI for glowstone im missing the mixer tab when i look

![image](https://github.com/MindBrain27/Sky-Greg/assets/699986/d347f412-5087-4ddd-9d25-05cf7dead5b3)

**Comment by MindBrain27** [comment]
That's strange... does the recipe i showed work still? I feel like it still works but is hidden on your side for some reason. I realized what was causing it and It hopefully should stop things like this but there is an open issue for this on the GTCEu Modern github page too, there is a GregTech update available as of today that I'm hoping it fixes these issues.

Also I should always respond within the day.

**Comment by TheMilso** [comment]
yes they still work fine.

**Comment by akasia** [comment]
and obsidian plate olso missing

**Comment by MindBrain27** [comment]
> and obsidian plate olso missing

Thanks, got that one, it doesn't seem to be hidden it's just missing in general. Will be changed next update.

**Comment by xyrc1** [comment]
Hi, I noticed the Soldering Alloy Dust recipe is also missing in the Mixer.
![image](https://github.com/MindBrain27/Sky-Greg/assets/75494811/b039a74d-fe35-4af1-83e4-ee0df9363767)
The recipe is the component dust ratio with Programmed Circuit on 3 in an LV Mixer if anyone else experiences this problem.

**Comment by MindBrain27** [comment]
Lots of Mixer dusts are hidden, I'm working on them now, likely the recipe exists it is just hidden.

A tip to anyone reading this, check the uses on the output item (Soldering Alloy Dust) and see the Centrifuge recipe, that is the dust mixture.

Next update will address most hidden recipes.

**Comment by TheMilso** [comment]
Soldering Allot is also not working or listed.
tried 9 tin and 1 antimony in an lv smelter.

**Comment by MindBrain27** [comment]
Try mixer with dusts. A lot of alloys are Mixer with dusts.

It's 6 Tin Dust, 3 Lead Dust and 1 Antimony Dust.

**Comment by MindBrain27** [comment]
New update should be out today (soon) and I'm going to mark this as closed for now but open another issue for ongoing missing recipes as I feel it may be an issue. TY everyone and please let me know if you see more.
