### ISSUE TITLE
Latest Update Wiremill Change

### ISSUE THREAD

**Issue by adk95** [MindBrain27/Sky-Greg#72]
In 1.24 the Wiremill has a UI bug where circuit is shown in output slot and the output goes in the input slot,
It works correctly its just the UI bug
![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/a697080a-3bcc-4835-bb3e-4de19e42792e)

**Comment by MindBrain27** [comment]
I saw this in the discord last night, there should be a follow up GT update soon to fix that, they usually release an update then some fixes the day or two after, as long as it still works for now it's ok but it shouldn't last long. They did have updates regarding the Wiremill too so they definitely messed something up.

**Comment by MindBrain27** [comment]
Try to break and re place the block, apparently that works.
