### ISSUE TITLE
The word "benefits" is misspelled as "bennifits"

### ISSUE THREAD

**Issue by projectNoob** [MindBrain27/Sky-Greg#73]
![Screenshot 2024-03-31 161929](https://github.com/MindBrain27/Sky-Greg/assets/82269729/67d8f820-4b4c-49da-b150-ffbb44544670)

**Comment by MindBrain27** [comment]
Got it, thank you! It's probably not the only one lol.

**Comment by MindBrain27** [comment]
Changed with newest update, feel free to open another case with more typos if you find any.
