### ISSUE TITLE
Large Bronze Boiler Consumes Lot of Lava in 1.24 

### ISSUE THREAD

**Issue by adk95** [MindBrain27/Sky-Greg#74]
1 Netherite lava source cannot handle full throttle large bronze boiler

![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/55f3a5d1-83dd-4bd1-9cfe-7a1dd735aa0e)

![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/40d94cc8-7815-4a8f-a843-e0170221130d)

![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/33f78f9d-a37e-43d2-9fd1-e4b20b478760)

**Comment by MindBrain27** [comment]
From a recent GT update,
"fix large boiler fuel consumption and steam output display"
I think they either weren't consuming enough lava before, or they broke something when they tried to fix something.

**Comment by adk95** [comment]
I am now just using the natural fluid generator to get lava its very nicely buffed can sustain a lot of steam boilers , also wanted to ask you as the functional storage mod was added will the storage drawers get removed or not since in many places i am using it.

**Comment by MindBrain27** [comment]
Both drawer mods will stay, at least for now, no need to change unless you want to, most people wanted it for the pushing/pulling upgrades which are quite nice for automations.
