### ISSUE TITLE
Recipe Conflict for  steel gearbox casing and solid steel machine casing which does not have a use 

### ISSUE THREAD

**Issue by adk95** [MindBrain27/Sky-Greg#76]
Steel Gearbox casing
![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/6d1653b5-8dc0-4546-bbd2-4f24b462c58c)

Solid Steel Machine Casing

![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/394c7cd7-8604-4e97-92ce-80d5ed63ec4c)

Both are made in circuit 4 if you request multiple gearbox casing it crafts the solid steel machine casing instead

**Comment by adk95** [comment]
Just found out that steel gearbox casing is not being crafted with circuit 4 at all
![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/490c982f-7578-4307-a824-7378da82b687)

**Comment by MindBrain27** [comment]
Fixed for next update.
