### ISSUE TITLE
Missing REI recipes (hidden in REI)

### ISSUE THREAD

**Issue by MindBrain27** [MindBrain27/Sky-Greg#8]
REI is missing recipes for some valid recipes, most notably with the Mixer but there are probably more as well. The problem exists when a recipe calls for a tagged item input and the tagged input has an item that is hidden in REI, like Ender Pearl Dust, Iron Dust, Gold Dust, and so on. With AE2 and EnderIO having some shared tags as GregTech it is causing some issues. This was the case for almost every progression Mixer alloy dust recipe, like Blue Steel, Black Steel, Black Bronze, Rose Gold, Stainless Steel, and so on.

Please post any missing recipes you find here, also note that the recipes still work, they just don't show.

**Comment by TheMilso** [comment]
Soldering Alloy is missing a recipe.
Tried the one I remember but its not working as well.
Tin and Antimony

**Comment by TheMilso** [comment]
Also Annealed Copper

**Comment by MindBrain27** [comment]
I've added the Soldering Alloy, but Annealed Copper should be in there, check uses for Copper Ingots in the Arc Furnace, 1 Copper Ingot and 63 mb of Oxygen. It's just hard to see in all the Arc Furnace Recipes.

**Comment by TheMilso** [comment]
Nope its not there i look at it and no furnace tab.
![image](https://github.com/MindBrain27/Sky-Greg/assets/699986/8a496fee-0eb3-41c1-afaa-3db32db7db61)

**Comment by TheMilso** [comment]
OH!! i was looking for its in blast furnace.

**Comment by MindBrain27** [comment]
Took me forever to find originally in the Arc Furnace list of 20 pages lol.

**Comment by TheMilso** [comment]
also missing iron 3 chloride 
![image](https://github.com/MindBrain27/Sky-Greg/assets/699986/f6210ded-6098-42bb-a5a5-2f739df1f776)

**Comment by MindBrain27** [comment]
Anyone know the recipe for Iron iii Chloride? It's not on the old GregTech wiki and I have no idea what it is.

**Comment by TheMilso** [comment]
Saturating Item
Not sure if its a missing recipe or something is off or quest description is misleading 
Quest just says add a potato to a sick.
![image](https://github.com/MindBrain27/Sky-Greg/assets/699986/16f679c7-e432-4cf3-a272-3aa8df949113)
This is only one i see And most of these parts don't have a way to make

**Comment by TheMilso** [comment]
Stainless steel is missing as well.

**Comment by MindBrain27** [comment]
A, You shouldn't see that Smithing Table recipe, it should be mush easier than that.
B, I'm very confused how both of those recipes are off for you.

If you right click on the instance icon in CurseForge and press Open Folder, do you see a folder named "kubejs"?

![image](https://github.com/MindBrain27/Sky-Greg/assets/74363414/5f76e51a-115f-40bb-b2a4-7f0fc84cf2a5)

In that folder should be a folder called "server_scripts", and then finally within that folder a file named 
"General Server Scripts".

By the sounds of it, it sounds like this is missing for you. This is what contains all of the recipe changes, both of those should be changed already. Let me know if that is missing because that is the only thing I can think of right now. It is present on my current playtest world however.

**Comment by MindBrain27** [comment]
you should be seeing 
![image](https://github.com/MindBrain27/Sky-Greg/assets/74363414/9501b03f-897f-4e7d-baee-8293e67dcf17)

and

![image](https://github.com/MindBrain27/Sky-Greg/assets/74363414/e16a278d-549e-4b30-9651-3e795e5bbb9e)

**Comment by TheMilso** [comment]
deleted that folder and updated to 1.0.8 most appear to be working now.

**Comment by akasia** [comment]
coal dust recipe missing on use only left crafting recpie
![2024-01-07_21 37 34](https://github.com/MindBrain27/Sky-Greg/assets/14824981/8c2c0495-a976-40cb-83e9-f0fdf891dfaf)

**Comment by MindBrain27** [comment]
Interesting, even if I get rid of the dye recipe I added, it still shows nothing else, I'm going to look into this more but it's different than the rest.

**Comment by DEMAXGAMER195** [comment]
Hi, I just updated to 1.09 and the recipe for kanthal dust is missing so one cant advance to HV.
I am now looking through all the dusts to see if any other are missing. I'll let you know if I find any.

**Comment by MindBrain27** [comment]
Interesting, some are literally going missing over time it seems.

The recipe still works but isn't displayed.

It's 1 Iron Dust, 1 Aluminium Dust, and 1 Chromium Dust in an MV Mixer with a Circuit of 1.

I just fixed Kanthal Dust and Bronze Dust.

**Comment by DEMAXGAMER195** [comment]
Thank you, I already thought they just where invisible but I still went through all of the dusts and what I found:
These materials are either invisible or unobtainable and crucial to progression:
-Kanthal^^
-Yttrium barium cuprate
-Mercury barium calcium cuprate
-Samarium iron arsenic oxide
-Indium tin barium titanium cuprare
-HSS E
-Zeron 100
-Watertight steel
-Maraging steel 300
-Hastealloy X
-Stellite 100
-Hastealloy C276
Also some dusts are craftable but have no mixer recipe. There is no problem in that, but it would be nice for cosistency.

**Comment by MindBrain27** [comment]
Thank you sooo much for this, I will work on them now. Just FYI if you need to know how to make a missing dust recipe, check the uses in the Centrifuge and it will usually show the dust combination. It seems like all of the progression Mixer dusts are hidden for whatever reason.

**Comment by DEMAXGAMER195** [comment]
In the past week I really enjoyed your modpack and the least I can do is help you continuing it, so thank you for making this possible.

**Comment by MindBrain27** [comment]
All fixed, should be an update tonight or tomorrow.

**Comment by akasia** [comment]
is this recipe conflict?
same ciruit conf 1

![2024-01-10_09 13 43](https://github.com/MindBrain27/Sky-Greg/assets/14824981/16931bc6-5312-475e-a50d-ac16ac486387)
![2024-01-10_09 13 44](https://github.com/MindBrain27/Sky-Greg/assets/14824981/d453f3fd-7b29-4d9e-9d76-284643b6be23)
![2024-01-10_09 13 47](https://github.com/MindBrain27/Sky-Greg/assets/14824981/d54f8658-e04f-4c03-b897-ed4380bd3282)
![2024-01-10_09 13 48](https://github.com/MindBrain27/Sky-Greg/assets/14824981/b6b8e0e8-df19-4704-80a9-ef42761b662d)

**Comment by MindBrain27** [comment]
One is Propane and one is Propene, one has an a and one has an e.

**Comment by akasia** [comment]
oh zzz >"<

**Comment by MindBrain27** [comment]
> coal dust recipe missing on use only left crafting recpie ![2024-01-07_21 37 34](https://private-user-images.githubusercontent.com/14824981/294761507-8c2c0495-a976-40cb-83e9-f0fdf891dfaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDQ1ODUsIm5iZiI6MTcwNTAwNDI4NSwicGF0aCI6Ii8xNDgyNDk4MS8yOTQ3NjE1MDctOGMyYzA0OTUtYTk3Ni00MGNiLTgzZTktZjBmZGY4OTFkZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwMTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NGIyYjE3YzMzYzliNjhkMmEzMWVhODg0MmUyMzZhMTcxN2E1YWNmNjhhMzYyMjVkODE2MTkxYzY0YmIyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hl5YSjyAPAWdVdiPaPXpAzUyUpdlYTOmu8tdhqQJX3o)

I finally fixed this one, and a few others.

**Comment by MindBrain27** [comment]
I have finally found the root of this problem and fixed hopefully all. Everything has to do with item tags and being hidden, EnderIO had a bunch of hidden items causing issues, all original dust recipes should be back now, if some dusts seem uncraftable, check the molten recipe as some are in the ABS (next update). Going forward I know the exact issue now so it should be easier to solve.

**Comment by MindBrain27** [comment]
Completely fixed with next update.
