### ISSUE TITLE
EV Energy Generation

### ISSUE THREAD

**Issue by Biomaxbr** [MindBrain27/Sky-Greg#82]
This is my first time playing with GregTech, so i'm a little confuse right now.

The guestline was been awesome to guide me until the EV Age, but now i don't know how to proceed to generate EV energy needed to power some machines, like EV Cutter to make MPIC.
I've already tried to connect 4 HV combustion engine in the cutter, but itsn't enough to supply 2048 EU/t and the recipe don't complete.
I think i'm missing something basic from the mod, but i don't know what it is. How can i make EV energy?

**Comment by poper12111** [comment]
What you need is a high voltage transformer to step up the voltage from 4 amps of hv to 1 amp of ev power

**Comment by Biomaxbr** [comment]
I had already tried this BUT after your reply I was doing some tests and realized that the transformer has two modes (use screwdriver) lol. I was turning 1A EV into 4A HV on my first attempt at using it D:
Thanks for the reply, it helped a lot.

[Suggestion] Add this to the quest book to make it easier for people like me.
