### ISSUE TITLE
is any know how to use laserio card cloner?

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#9]
is any know how to use laserio card cloner? can't find any toturiol on wedside

**Comment by MindBrain27** [comment]
This should help it's a spotlight by the mod author

https://www.youtube.com/watch?v=o22Pq9NmTSY

I am going to also add a small LaserioIO chapter soon.

**Comment by MindBrain27** [comment]
https://www.youtube.com/watch?v=6KomZPRD1GM

Here is an updated 1.20 video as well.

**Comment by akasia** [comment]
direwolf did't say about card cloner that 2 vid spotlight i has seem b4 but never mantion about card cloner 
and i can't find it on any wedside olso

**Comment by MindBrain27** [comment]
I'll see what I can figure out and document later tonight. I'll post here and also make quest but after work.

**Comment by MindBrain27** [comment]
Open a Node containing Cards, hold the Card Cloner with your mouse, left click on the Card you want to copy and right click on the Card you want to paste.

It will copy the settings from the Card you left click and paste them on the Card you right click.

**Comment by akasia** [comment]
oh that it? i try later
